// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'
	| 'pt'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	// 	/**
	//  * H​e​l​l​o​ ​{​n​a​m​e​}​!
	//  * @param {string} name
	//  */
	// 	hi: RequiredParams<'name'>
}

export type TranslationFunctions = {
	hi: (arg: { name: string }) => LocalizedString,
	audio: {
		notfound: (arg: { audioMinutes: number }) => LocalizedString,
		finished: (arg: { summary: string, transcription: string, balance: number }) => LocalizedString,
		prompt: () => LocalizedString,
	},
	user: {
		balance: (arg: { name: string, balance: number }) => LocalizedString,
		created: (arg: { name: string, balance: number, audioMinutes: number }) => LocalizedString,
		alreadyregistered: (arg: { name: string, balance: number, audioMinutes: number }) => LocalizedString,
		default: (arg: { audioMinutes: number }) => LocalizedString,
	}
}

export type Formatters = {}
